#!/bin/bash
# Nome: data-flow-mapper.sh
# Uso: ./data-flow-mapper.sh
# Resultado: Mostra fluxo de dados por rota (SEM EDITOR)

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                   ORBIT DASHBOARD — DATA FLOW MAP                         ║"
echo "║                      (Todas as Rotas + Componentes)                       ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "ROTA: /"
echo "├─ Arquivo: src/app/page.tsx (RootPage)"
echo "├─ Componente: RootPage"
echo "├─ Props: Nenhuma"
echo "├─ Dados Recebidos:"
echo "│  └─ supabase.auth.getSession() → { session: Session | null }"
echo "├─ Lógica:"
echo "│  ├─ Se session existe → router.push('/instagram')"
echo "│  └─ Se session vazio → Renderiza formulário de login"
echo "├─ Renderiza:"
echo "│  └─ <form> com inputs email/password"
echo "├─ Fluxo Saída:"
echo "│  └─ handleLogin() → supabase.auth.signInWithPassword()"
echo "└─ Próxima Rota: /instagram (após login bem-sucedido)"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "ROTA: /instagram"
echo "├─ Arquivo: src/app/instagram/page.tsx (InstagramOverviewPage)"
echo "├─ Componente: InstagramOverviewPage"
echo "├─ Props: Nenhuma"
echo "├─ Dados Recebidos:"
echo "│  ├─ CLIENTS (hardcoded array com 2 clientes)"
echo "│  ├─ PERIOD_START = new Date('2026-01-01')"
echo "│  └─ PERIOD_END = new Date()"
echo "├─ Lógica:"
echo "│  ├─ activeClientKey = useState(clientIds[0])"
echo "│  ├─ activeClient = CLIENTS[activeClientKey]"
echo "│  └─ Renderiza: <OrbitDashboardProvider clientId={activeClient.id}>"
echo "├─ Renderiza:"
echo "│  ├─ <nav> com seletor de clientes (2 botões)"
echo "│  └─ <InstagramOverviewLayout /> (componente filho)"
echo "├─ Fluxo Saída:"
echo "│  └─ setActiveClientKey() → Remonta OrbitDashboardProvider"
echo "└─ Componentes Filhos: InstagramOverviewLayout"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "COMPONENTE: InstagramOverviewLayout"
echo "├─ Arquivo: src/app/instagram/page.tsx (dentro de page.tsx)"
echo "├─ Props:"
echo "│  └─ Nenhuma (usa useOrbitDashboard() hook)"
echo "├─ Dados Recebidos:"
echo "│  ├─ useOrbitDashboard() → { data, status, error, activeTab }"
echo "│  └─ data: IGOverviewData (KPIs, qualityScores, formatPerformance, insights)"
echo "├─ Lógica:"
echo "│  ├─ Se status === 'loading' → Renderiza spinner"
echo "│  ├─ Se status === 'error' → Renderiza erro"
echo "│  ├─ Se status === 'success' → Renderiza dashboard"
echo "│  └─ activeTab determina qual tela mostrar (overview, por-post, audiencia)"
echo "├─ Renderiza:"
echo "│  ├─ <Sidebar /> (navegação lateral)"
echo "│  ├─ <Header /> (cabeçalho com handle)"
echo "│  ├─ <main> com 3 telas:"
echo "│  │  ├─ overview: <KPICard> + <QualityScoresPanel> + <FormatPerformanceTable>"
echo "│  │  ├─ por-post: <FormatPerformanceTable>"
echo "│  │  └─ audiencia: <QualityScoresPanel> + Avatar Alignment (FUTURO)"
echo "│  └─ <CriticalAlert> (se houver alertas)"
echo "├─ Fluxo Saída:"
echo "│  └─ Sidebar.tsx → setActiveTab() → Remonta <main>"
echo "└─ Componentes Filhos: Sidebar, Header, KPICard, QualityScoresPanel, FormatPerformanceTable"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "ROTA: /avatar"
echo "├─ Arquivo: src/app/avatar/page.tsx (AvatarPage)"
echo "├─ Componente: AvatarPage"
echo "├─ Props: Nenhuma"
echo "├─ Dados Recebidos:"
echo "│  ├─ CLIENTS (hardcoded array)"
echo "│  ├─ PERIOD_START, PERIOD_END"
echo "│  └─ activeClientKey = useState()"
echo "├─ Lógica:"
echo "│  ├─ Renderiza: <OrbitDashboardProvider clientId={activeClient.id}>"
echo "│  └─ Renderiza: <AvatarScreen /> (componente filho)"
echo "├─ Renderiza:"
echo "│  ├─ <nav> com seletor de clientes"
echo "│  └─ <AvatarScreen />"
echo "├─ Fluxo Saída:"
echo "│  └─ setActiveClientKey() → Remonta OrbitDashboardProvider"
echo "└─ Componentes Filhos: AvatarScreen"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "COMPONENTE: AvatarScreen"
echo "├─ Arquivo: src/components/screens/AvatarScreen.tsx"
echo "├─ Props:"
echo "│  └─ clientId: string (recebido via OrbitDashboardProvider context)"
echo "├─ Dados Recebidos:"
echo "│  ├─ useAvatar(clientId) → { data, status, error }"
echo "│  └─ data: AvatarAlignment (expected, real, scores)"
echo "├─ Lógica:"
echo "│  ├─ Se !clientId → Renderiza: 'Cliente não identificado'"
echo "│  ├─ Se status === 'loading' → Renderiza: <AvatarScreenSkeleton />"
echo "│  ├─ Se status === 'error' → Renderiza: <ErrorBoundary>"
echo "│  └─ Se status === 'success' → Renderiza: <AvatarComparison>"
echo "├─ Renderiza:"
echo "│  └─ <AvatarComparison expected={data.expected} real={data.real} />"
echo "├─ Fluxo Saída:"
echo "│  └─ AvatarComparison renderiza 2 AvatarCards + Score"
echo "└─ Componentes Filhos: AvatarComparison"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "COMPONENTE: AvatarComparison"
echo "├─ Arquivo: src/components/avatar/AvatarComparison.tsx"
echo "├─ Props:"
echo "│  ├─ expected: AvatarProfile"
echo "│  └─ real: AvatarProfile"
echo "├─ Dados Recebidos:"
echo "│  ├─ Props (expected, real)"
echo "│  └─ Nenhuma chamada de API"
echo "├─ Lógica:"
echo "│  ├─ Renderiza: <AvatarCard variant=\"expected\" profile={expected} />"
echo "│  ├─ Renderiza: <AvatarCard variant=\"real\" profile={real} />"
echo "│  └─ Calcula score de alinhamento"
echo "├─ Renderiza:"
echo "│  ├─ <div> com 2 cards lado a lado"
echo "│  └─ <div> com score de alinhamento"
echo "├─ Fluxo Saída:"
echo "│  └─ Nenhuma (componente burro, apenas renderiza)"
echo "└─ Componentes Filhos: AvatarCard (2x)"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "ROTA: /alertas"
echo "├─ Arquivo: src/app/alertas/page.tsx (AlertasPage)"
echo "├─ Componente: AlertasPage"
echo "├─ Props: Nenhuma"
echo "├─ Dados Recebidos:"
echo "│  ├─ useOrbitDashboard() → { data }"
echo "│  └─ data.criticalAlerts: CriticalAlertData[]"
echo "├─ Lógica:"
echo "│  └─ Renderiza lista de alertas"
echo "├─ Renderiza:"
echo "│  └─ <CriticalAlert> (múltiplos)"
echo "└─ Componentes Filhos: CriticalAlert"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "ROTA: /carteira"
echo "├─ Arquivo: src/app/carteira/page.tsx (CarteiraPage)"
echo "├─ Componente: CarteiraPage"
echo "├─ Props: Nenhuma"
echo "├─ Dados Recebidos:"
echo "│  ├─ useOrbitDashboard() → { data }"
echo "│  └─ data: IGOverviewData"
echo "├─ Lógica:"
echo "│  └─ Renderiza dados de carteira/clientes"
echo "├─ Renderiza:"
echo "│  └─ <ClientCard> (múltiplos)"
echo "└─ Componentes Filhos: ClientCard"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "ROTA: /funil"
echo "├─ Arquivo: src/app/funil/page.tsx (FunilPage)"
echo "├─ Componente: FunilPage"
echo "├─ Props: Nenhuma"
echo "├─ Dados Recebidos:"
echo "│  ├─ useOrbitDashboard() → { data }"
echo "│  └─ data: IGOverviewData"
echo "├─ Lógica:"
echo "│  └─ Renderiza funil de e-commerce"
echo "├─ Renderiza:"
echo "│  └─ <FunilChart>"
echo "└─ Componentes Filhos: FunilChart"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "ROTA: /_not-found"
echo "├─ Arquivo: src/app/not-found.tsx"
echo "├─ Componente: NotFound"
echo "├─ Props: Nenhuma"
echo "├─ Dados Recebidos: Nenhuma"
echo "├─ Lógica:"
echo "│  └─ Renderiza página 404"
echo "├─ Renderiza:"
echo "│  └─ <div> com mensagem de erro"
echo "└─ Componentes Filhos: Nenhum"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "FLUXO DE DADOS COMPLETO (L0 → L5):"
echo ""
echo "L0 (DATA — Banco):"
echo "  ├─ Supabase: orbit.clients, orbit.v_kpi_snapshots, orbit.v_quality_scores"
echo "  └─ Supabase: orbit.v_format_performance, orbit.ig_audience_snapshots"
echo ""
echo "L1 (INFORMATION — Repositório):"
echo "  ├─ instagramOverviewRepository.ts"
echo "  ├─ fetchKPIs() → KPICardData[]"
echo "  ├─ fetchQualityScores() → QualityScoreItem[]"
echo "  └─ fetchFormatPerformance() → FormatPerformanceRow[]"
echo ""
echo "L2 (KNOWLEDGE — Hook):"
echo "  ├─ useOrbitDashboard() → { data: IGOverviewData, status, error }"
echo "  └─ useAvatar() → { data: AvatarAlignment, status, error }"
echo ""
echo "L3 (WISDOM — Context):"
echo "  ├─ OrbitDashboardContext"
echo "  ├─ Armazena: data, status, error, activeTab"
echo "  └─ Fornece: useOrbitDashboard() hook"
echo ""
echo "L4 (SCREENS — Páginas):"
echo "  ├─ InstagramOverviewPage → Renderiza dashboard"
echo "  ├─ AvatarPage → Renderiza avatar alignment"
echo "  └─ AlertasPage, CarteiraPage, FunilPage"
echo ""
echo "L5 (UI — Componentes):"
echo "  ├─ KPICard, QualityScoresPanel, FormatPerformanceTable"
echo "  ├─ AvatarCard, AvatarComparison"
echo "  ├─ Sidebar, Header, CriticalAlert"
echo "  └─ ClientCard, FunilChart"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"