-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agencies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  phone text,
  website text,
  country text,
  timezone text NOT NULL DEFAULT 'America/Sao_Paulo'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agencies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  auth_id uuid NOT NULL UNIQUE,
  email text NOT NULL,
  full_name text,
  role text NOT NULL DEFAULT 'viewer'::text CHECK (role = ANY (ARRAY['admin'::text, 'editor'::text, 'viewer'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);
CREATE TABLE public.kpi_raw_ingestion (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid,
  agency_id uuid NOT NULL,
  source text NOT NULL CHECK (source = ANY (ARRAY['instagram_graph_api'::text, 'meta_ads_api'::text, 'meta_ads_export'::text, 'google_ads_api'::text])),
  api_version text NOT NULL,
  endpoint text NOT NULL,
  collected_at timestamp with time zone NOT NULL DEFAULT now(),
  period_start date NOT NULL,
  period_end date NOT NULL,
  raw_payload jsonb NOT NULL,
  payload_size_kb integer DEFAULT (octet_length((raw_payload)::text) / 1024),
  ingestion_status text NOT NULL DEFAULT 'pending'::text CHECK (ingestion_status = ANY (ARRAY['pending'::text, 'processed'::text, 'error'::text, 'skipped'::text])),
  error_detail text,
  schema_version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  product_type text,
  uses_original_audio boolean,
  video_duration_s numeric,
  CONSTRAINT kpi_raw_ingestion_pkey PRIMARY KEY (id),
  CONSTRAINT kpi_raw_ingestion_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT fk_raw_ingestion_client FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  name text NOT NULL,
  instagram_account_id text,
  meta_ads_account_id text,
  is_business_account boolean NOT NULL DEFAULT false,
  avatar_gender_expected text,
  avatar_age_range_expected text,
  avatar_city_expected text,
  benchmark_cpm_l2 numeric,
  benchmark_engagement_l2 numeric,
  benchmark_input_by uuid,
  benchmark_updated_at timestamp with time zone,
  ctr_threshold_meta numeric NOT NULL DEFAULT 1.0,
  ctr_threshold_google numeric NOT NULL DEFAULT 2.0,
  cpa_alert_multiplier numeric NOT NULL DEFAULT 1.5,
  freq_alert_threshold numeric NOT NULL DEFAULT 3.0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT clients_benchmark_input_by_fkey FOREIGN KEY (benchmark_input_by) REFERENCES public.users(id)
);
CREATE TABLE public.oauth_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['meta'::text, 'google'::text])),
  access_token text NOT NULL,
  token_type text NOT NULL DEFAULT 'bearer'::text,
  expires_at timestamp with time zone NOT NULL,
  scope text,
  meta_user_id text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT oauth_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_tokens_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);
CREATE TABLE public.kpi_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  metric text NOT NULL,
  value numeric,
  value_text text,
  source_level USER-DEFINED NOT NULL DEFAULT 'L1'::source_level,
  period_start date NOT NULL,
  period_end date NOT NULL,
  formula text,
  media_id text,
  ad_id text,
  raw_ref uuid,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT kpi_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT kpi_snapshots_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT kpi_snapshots_raw_ref_fkey FOREIGN KEY (raw_ref) REFERENCES public.kpi_raw_ingestion(id)
);
CREATE TABLE public.follower_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  week_start date NOT NULL,
  count integer NOT NULL,
  delta integer,
  streak_neg integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT follower_history_pkey PRIMARY KEY (id),
  CONSTRAINT follower_history_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.ads_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  ad_id text NOT NULL,
  week_index integer NOT NULL,
  week_start date NOT NULL,
  ctr numeric,
  cpa numeric,
  frequency numeric,
  fatigue_pct numeric,
  diagnosis USER-DEFINED,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ads_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT ads_metrics_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.alert_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL UNIQUE,
  ctr_threshold_meta numeric NOT NULL DEFAULT 1.0,
  ctr_threshold_google numeric NOT NULL DEFAULT 2.0,
  cpa_multiplier numeric NOT NULL DEFAULT 1.5,
  freq_threshold numeric NOT NULL DEFAULT 3.0,
  alert_email text,
  alert_slack_webhook text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT alert_config_pkey PRIMARY KEY (id),
  CONSTRAINT alert_config_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.domain_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  event_type USER-DEFINED NOT NULL,
  previous_state jsonb,
  new_state jsonb,
  triggered_at timestamp with time zone NOT NULL DEFAULT now(),
  webhook_sent boolean NOT NULL DEFAULT false,
  webhook_url text,
  webhook_response jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT domain_events_pkey PRIMARY KEY (id),
  CONSTRAINT domain_events_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.benchmark_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  metric_name text NOT NULL,
  benchmark_value numeric NOT NULL,
  source_level USER-DEFINED NOT NULL DEFAULT 'L2'::source_level,
  input_by uuid NOT NULL,
  input_reason text,
  valid_from date NOT NULL DEFAULT CURRENT_DATE,
  valid_until date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT benchmark_history_pkey PRIMARY KEY (id),
  CONSTRAINT benchmark_history_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT benchmark_history_input_by_fkey FOREIGN KEY (input_by) REFERENCES public.users(id)
);
CREATE TABLE public.lead_raw_ingestion (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_external_id text NOT NULL,
  agency_id text NOT NULL,
  client_id text NOT NULL,
  ingestion_mode text NOT NULL DEFAULT 'lead'::text,
  product_type text,
  product_type_detail text,
  posted_at timestamp with time zone NOT NULL,
  caption_text text,
  hashtags jsonb DEFAULT '[]'::jsonb,
  is_pinned boolean DEFAULT false,
  location_name text,
  uses_original_audio boolean,
  audio_name text,
  is_coautoria boolean DEFAULT false,
  tipo_narrativa text,
  likes_count integer,
  comments_count integer NOT NULL DEFAULT 0,
  video_play_count integer,
  video_view_count integer,
  video_duration_s numeric,
  play_rate numeric,
  comment_signals jsonb DEFAULT '{}'::jsonb,
  tagged_users jsonb DEFAULT '[]'::jsonb,
  ingested_at timestamp with time zone DEFAULT now(),
  source_file text,
  CONSTRAINT lead_raw_ingestion_pkey PRIMARY KEY (id)
);