$json = Get-Content 'C:\Projetos\orbit-dashboard\dataset_instagram-scraper_2026-09-23_14-25-01-398.json' | ConvertFrom-Json;
$total_posts = ($json | ForEach-Object { $_.posts.Count } | Measure-Object -Sum).Sum;
$video_view_count_present = ($json | ForEach-Object { $_.posts | Where-Object { $_.video_view_count -ne $null } | Measure-Object).Count;
$latest_comments_present = ($json | ForEach-Object { $_.posts | Where-Object { $_.latest_comments -ne $null -and $_.latest_comments.Count -gt 0 } | Measure-Object).Count;
$anomalies_present = ($json | ForEach-Object { $_.posts | Where-Object { $_.anomalies -ne $null -and $_.anomalies.Count -gt 0 } | Measure-Object).Count;
Write-Host '📊 VALIDAÇÃO DE CAMPOS CRÍTICOS' -ForegroundColor Cyan;
Write-Host "Total de posts: $total_posts" -ForegroundColor White;
Write-Host "Posts com video_view_count: $video_view_count_present ($([math]::Round($video_view_count_present/$total_posts*100, 2))%)" -ForegroundColor Green;
Write-Host "Posts com latest_comments: $latest_comments_present ($([math]::Round($latest_comments_present/$total_posts*100, 2))%)" -ForegroundColor Green;
Write-Host "Posts com anomalies: $anomalies_present ($([math]::Round($anomalies_present/$total_posts*100, 2))%)" -ForegroundColor Yellow;
Write-Host '';
Write-Host '📋 AMOSTRA: video_view_count (primeiros 5)' -ForegroundColor Magenta;
$json | ForEach-Object { $_.posts | Where-Object { $_.video_view_count -ne $null } | Select-Object -First 5 -ExpandProperty video_view_count };
Write-Host '';
Write-Host '💬 AMOSTRA: latest_comments (primeiros 3 posts)' -ForegroundColor Magenta;
$json | ForEach-Object { $_.posts | Where-Object { $_.latest_comments -ne $null -and $_.latest_comments.Count -gt 0 } | Select-Object -First 3 -ExpandProperty latest_comments };
Write-Host '';
Write-Host '⚠️ AMOSTRA: anomalies (primeiros 3)' -ForegroundColor Red;
$json | ForEach-Object { $_.posts | Where-Object { $_.anomalies -ne $null -and $_.anomalies.Count -gt 0 } | Select-Object -First 3 -ExpandProperty anomalies };
